### ISSUE TITLE
`HyperspectralCube.flags` was removed from astropy.nddata.NDData

### ISSUE THREAD

**Issue by Linkid** [irap-omp/hyperspectral#1]
The `flags` property was removed from `astropy.nddata.NDData` (https://github.com/astropy/astropy/commit/bda7773c74bd150e6fb7b4da3cd5ef3f853c90d1) in the tag v1.0rc2. So, 12 tests are failing.
2 solutions:
- specify the required version of `astropy` (the version could be the second to last in PyPI: 0.4.5);
- use one usefull arguments in your init class (for example, it seems that `flags` is never used).

**Comment by Goutte** [comment]
Thanks for this !

I had no time to update this package since `astropy` has been bumped to 1.0. `hyperspectral` is not a polished package yet, there are stil many issues and shortcoming to solve (like FSCALE management, and a better usage of astropy's WCS object)

It should/will be compatible with the `1.x` series of astropy.

I will find some time in April to fix those, but not sooner.

**Comment by Goutte** [comment]
Ok, I fixed the BC breaks. Test suite now runs. Thanks again for the tip ;)
